apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ad-service-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - worldtoday.shop
    - www.worldtoday.shop  # Added www subdomain support
    secretName: worldtoday-shop-tls 
  rules:
  - host: worldtoday.shop
  - host: www.worldtoday.shop
    http:
      paths:
      - path: /.well-known/acme-challenge/
        pathType: Prefix
        backend:
          service:
            name: cm-acme-http-solver  # LetsEncrypt challenge solver
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ad-service
            port:
              number: 3002
      - path: /api/ads
        pathType: Prefix
        backend:
          service:
            name: ad-service
            port:
              number: 3002
      - path: /api/dashboard
        pathType: Prefix
        backend:
          service:
            name: ad-service
            port:
              number: 3002
  - host: www.worldtoday.shop  # Added rule for www subdomain
    http:
      paths:
      - path: /.well-known/acme-challenge/
        pathType: Prefix
        backend:
          service:
            name: cm-acme-http-solver  # LetsEncrypt challenge solver
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ad-service
            port:
              number: 3002