apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ad-service-ingress
  namespace: default  # Add this if not already implied
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.worldtoday.shop  # Change to api subdomain
      secretName: worldtoday-shop-tls
  rules:
    - host: api.worldtoday.shop  # Change to api subdomain
      http:
        paths:
          - path: /.well-known/acme-challenge/
            pathType: Prefix
            backend:
              service:
                name: cm-acme-http-solver
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ad-service
                port:
                  number: 3002
          - path: /api/ads
            pathType: Prefix
            backend:
              service:
                name: ad-service
                port:
                  number: 3002
          - path: /api/dashboard
            pathType: Prefix
            backend:
              service:
                name: ad-service
                port:
                  number: 3002
