apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: 404456670711.dkr.ecr.us-east-1.amazonaws.com/user-service:latest  
        ports:
        - containerPort: 3001
        env:
        - name: MONGODB_URI
          value: "mongodb+srv://afsalap:kvrsalus123@cluster0.xmzan.mongodb.net/user-service?retryWrites=true&w=majority&appName=Cluster0"
        - name: JWT_SECRET
          value: "afsal390ap"
        - name: JWT_REFRESH_SECRET
          value: "afsal390ap"
        - name: TWILIO_ACCOUNT_SID
          valueFrom:
            secretKeyRef:
              name: twilio-secret
              key: account_sid 
        - name: TWILIO_AUTH_TOKEN
          value: "6e87302a27e4de8f64a413dc5c12f072"
        - name: TWILIO_PHONE_NUMBER
          value: "+18153174341" 
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: stripe-secret
              key: STRIPE_SECRET_KEY
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@rabbitmq-service:5672" 
        - name: STRIPE_WEBHOOK_SECRET
          value: "whsec_ccfc02dc90a4d77cc8e0c24e7570fd6a4c6bf744ee00d916fa98dabbef83e17c "
